title: "Sammy Chuang"
author: "Sammy Chuang"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: false               # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "Games.md", icon: address-card}
  - {file: "3DModelling.md", icon: address-card}
  - {file: "Writings.md", icon: address-card}
  - {file: "Resume.md", icon: address-card}

#  - {file: "Contact.md", icon: address-card}

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:samantha.s.chuang@gmail.com"
  instagram: "https://www.instagram.com/penguincoco/"

external:                    # see http://fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
#  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
#  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed